### ISSUE TITLE
Ask inside the actor's Receive - await hangs, ContinueWith works.

### ISSUE THREAD

**Issue by pcwiek** [akkadotnet/akka.net#852]
Disclaimer: I'm using Akka.Cluster, one actor is issuing ask to remote actor ref.

1. I have local actor selection, which I `Ask` to do one thing. That `Ask` happens from the 'outside' of the actor system:

        // Somewhere outside
        var result = await localActorSelection.Ask<ThingResult>(new DoThing(1));

2. (Just for completeness) Remote actor:

        Receive<FetchPart>(msg => 
        {
            // Do some stuff, sometimes it's async, sometimes it uses internal child actors with original sender being carried around
            Sender.Tell(new PartOfTheThing());
        });

3. Inside the first actor, I handle the message and ask the remote actor for part of the 'thing':
    
        Receive<DoThing>(async msg => 
        {
             var partOfTheThing = await remoteActorSelection.Ask<PartOfTheThing>(new FetchPart(msg.Id));
             Sender.Tell(new ThingResult("Abc", partOfTheThing));
        });

Notice the `await remoteActorSelection.Ask<>` part - it hangs. The `Sender` in remote actor is something akin to `akka.tcp://my-system@127.0.0.1:22100/temp/e`.

Now, if I change the local actor's `Receive` to:

    Receive<DoThing>(msg => 
    {
         remoteActorSelection.Ask<PartOfTheThing>(new FetchPart(msg.Id)).ContinueWith(r =>
         {
             var partOfTheThing = r.Result;
             Sender.Tell(new ThingResult("Abc", partOfTheThing));
         }
    });

It works (?). The remote actor's reply goes into the continuation.

No matter whether I choose `Reentrant` or `Suspend` behavior, include `ConfigureAwait(false)` or not, `await` just sits there. There's no exception, nothing...

Thoughts? :)

**Comment by smalldave** [comment]
As I understand it that should work.

```csharp
Receive<DoThing>(async msg => 
{
     var partOfTheThing = await remoteActorSelection.Ask<PartOfTheThing>(new FetchPart(msg.Id));
     Sender.Tell(new ThingResult("Abc", partOfTheThing));
});
```
This looks a bit wrong though. Generally you want to avoid using Ask inside an actor.
You could pass the Sender on and have the remote actor reply directly to the Sender.

**caveat** you mentioned you were using Ask to call into the system. I've read that you can't call temporary actors from remote actor systems. I've never tried to do so. It may not work.

**Comment by pcwiek** [comment]
About the caveat, the only weird thing is that continuation works, but await doesn't, even though they use the same infrastructure  -correct me here if I'm wrong.

I might change it to tell & tell back, but that means that if I have (for example) 2 different remote calls, I'll have to 'carry' the state along (i.e. previous parts fetched in previous messages) till the very end until I'm able to compose full reply to the original sender...(?).

Assuming calls have to be done one after another, then this snippet:
    Receive(_ => {
        var part1 = await actor1.Ask<...>
        var part2 = await actor2.Ask<...>
        Sender.Tell(new FullThing("Abc", part1, part2));
    });

Would have to be broken down into something like (pseudocode :))

   Receive<OriginalMsg>(...)
   Receive<Tuple<OriginalMsg, Part1>>(...)
   Receive<Tuple<OriginalMsg, Part1, Part2>>(msg => // return to original sender)

I already assumed I would integrate 'original sender' into the message.
Of course instead of tuples I could use dedicated message classes, but I hope you can see it adds *quite a lot* of boilerplate, especially in C#.

Anyway, off to refactor, I'll probably do all 'tells' instead.

**Comment by rogeralsing** [comment]
Hi

Are you using the latest Dev bits?
We fixed some severe async await issues in the 1.0 release.

**Comment by pcwiek** [comment]
I installed Akka 1.0 from NuGet, including prerelease 1.0 version of Akka.Cluster.

**Comment by rogeralsing** [comment]
Ok, yes the async await is broken there, you need to either get the latest code from our dev branch or wait for our upcoming hotifx

**Comment by maurosampietro** [comment]
I still don't get the expected behavior. I'm very new to Akka and just playing around with the HelloWorld example on the main project's documentation page.

**I was just trying to wait for a response from the actor before doing anything else.**

Here is the complete code:

```
class Program
{
    static void Main( string[] args )
    {
        var system = ActorSystem.Create( "MySystem" );
        var greeter = system.ActorOf<BipolarActor>( "greeter" );

        MainAsyncLoop( greeter );

        Console.ReadLine();
    }

    private static async void MainAsyncLoop( IActorRef greeter )
    {
        while( true )
        {
            Console.Write( "What's your name?: " );
            var name = Console.ReadLine();

            await greeter.Ask( new AnswerPerson( name ) );

            Console.Write( "Change behavior? (y/f): " );
            var key = Console.ReadKey();

            if( key.Key == ConsoleKey.Y )
                await greeter.Ask( new ChangeBehavior() );
        }
    }
}

public class BipolarActor : ReceiveActor
{
    public BipolarActor()
    {
        Receive<AnswerPerson>( greet => Console.WriteLine( $"Hello {greet.Who}" ) );
        Receive<ChangeBehavior>( greet => Become( Rude ) );
    }

    private void Rude()
    {
        Receive<AnswerPerson>( fuck => Console.WriteLine( $"F**k you {fuck.Who}" ) );
    }
}

public class ChangeBehavior { }

public class AnswerPerson
{
    public readonly string Who;

    public AnswerPerson( string who )
    {
        Who = who;
    }
}

```

**Comment by 0x53A** [comment]
This is probably the same root cause as https://github.com/akkadotnet/akka.net/issues/2546
